In [18]:
# COMP9021 20T3 - Rachid Hamadi
# Quiz 6 *** Due Friday Week 9 @ 10.00pm

# DO *NOT* WRITE YOUR NAME TO MAINTAIN ANONYMITY FOR PLAGIARISM DETECTION

# Randomly generates a grid of 0s and 1s and determines
# the maximum number of "spikes" in a shape.
# A shape is made up of 1s connected horizontally or vertically (it can contain holes).
# A "spike" in a shape is a 1 that is part of this shape and "sticks out"
# (has exactly one neighbour in the shape).
# Neighbours are only considered vertically or horizontally (not diagonally).


from random import seed, randrange
import sys
import numpy as np
from collections import deque

dim = 10


def display_grid():
    for row in grid:
        print('   ', *row) 


# Returns the number of shapes we have discovered and "coloured".
# We "colour" the first shape we find by replacing all the 1s
# that make it with 2. We "colour" the second shape we find by
# replacing all the 1s that make it with 3.
def colour_shapes():

    (m,n)=(len(grid), len(grid[0]))
    visited=[[False for x in range(n)] for y in range(m)]

    row=[1,-1,0,0]
    col=[0,0,-1,1]

    def isSafe(grid, x, y, processed):
	    return (x >= 0) and (x < len(processed)) and \
		   (y >= 0) and (y < len(processed[0])) and \
		   (grid[x][y] == 1 and not processed[x][y])
                
    def BFS(grid, processed, i, j):

        # create an empty queue and enqueue source node
        q = deque()
        q.append((i, j))

        # mark source node as processed
        processed[i][j] = True

        # loop till queue is empty
        while q:

            # pop front node from queue and process it
            x, y = q.popleft()

            # check for all 8 possible movements from current cell
            # and enqueue each valid movement
            spike=0
            for k in range(4):
                # Skip if location is invalid or already processed or has water
                if isSafe(grid, x + row[k], y + col[k], processed):
                    # skip if location is invalid or it is already
                    # processed or consists of water
                    processed[x + row[k]][y + col[k]] = True
                    q.append((x + row[k], y + col[k]))

            #return spike
        
        
    processed = [[False for x in range(n)] for y in range(m)]
    island=0
    spikes=[]
    for i in range(m):
        for j in range(n):
            if grid[i][j]==1 and not processed[i][j]:
                
                prev_processed = 1*np.array(processed)
                #print('before\n',prev_processed)
                spikes.append(BFS(grid,processed,i,j))
                
                after_processed = 1*np.array(processed)
                #print('after\n',after_processed)
                
                new_island = after_processed - prev_processed
                print('new_island \n',new_island)
                print(count_spikes(new_island))
                island=island+1
    
    print(max(spikes))
                
    #print(np.matrix(grid))

def max_number_of_spikes(nb_of_shapes):
    pass
    # Replace pass above with your code


# Possibly define other functions here    


try: 
    for_seed, density = (int(x) for x in input('Enter two integers, the second '
                                               'one being strictly positive: '
                                              ).split()
                    )
    if density <= 0:
        raise ValueError
except ValueError:
    print('Incorrect input, giving up.')
    sys.exit()

seed(for_seed)
grid = [[int(randrange(density) != 0) for _ in range(dim)]
            for _ in range(dim)
       ]
print('Here is the grid that has been generated:')
display_grid()
nb_of_shapes = colour_shapes()
print('The maximum number of spikes of some shape is:',
      max_number_of_spikes(nb_of_shapes)
     )

Enter two integers, the second one being strictly positive: 0 8
Here is the grid that has been generated:
    1 1 0 1 1 1 1 1 1 1
    1 1 1 1 1 1 1 1 1 1
    1 1 1 1 1 1 1 1 1 0
    0 1 1 0 1 1 1 1 1 1
    1 1 1 1 1 1 1 1 1 1
    1 1 1 1 1 1 1 1 1 1
    1 1 1 1 0 1 1 1 1 1
    1 0 1 1 1 1 1 1 1 1
    1 1 1 1 1 1 1 1 1 0
    1 1 1 1 1 1 1 0 1 1
new_island 
 [[1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0]
 [0 1 1 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1]
 [1 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 0 1 1]]
1
None
The maximum number of spikes of some shape is: None


In [15]:
def count_spikes(new_island_matrix):
    
    spike_count = 0 
    for x in range(len(new_island_matrix)):
        for y in range(len(new_island_matrix[x])):
            if new_island_matrix[x][y]==1:
                if x==0:
                    if y==0:
                        if new_island_matrix[x+1][y]+new_island_matrix[x][y+1]== 1:
                            spike_count+=1
                    elif y==9:
                        if new_island_matrix[x+1][y]+new_island_matrix[x][y-1] == 1:
                            spike_count+=1
                    else:
                        if new_island_matrix[x+1][y]+new_island_matrix[x][y+1]+new_island_matrix[x][y-1] == 1:
                            spike_count+=1
                elif x==9:
                    if y==0:
                        if new_island_matrix[x-1][y]+new_island_matrix[x][y+1] == 1:
                            spike_count+=1
                    elif y==9:
                        if new_island_matrix[x-1][y]+new_island_matrix[x][y-1] == 1:
                            spike_count+=1
                    else:
                        if new_island_matrix[x-1][y]+new_island_matrix[x][y+1]+new_island_matrix[x][y-1] == 1:
                            spike_count+=1
                else:
                    if y==0:
                        if new_island_matrix[x+1][y]+ new_island_matrix[x-1][y]+new_island_matrix[x][y+1] == 1:
                            spike_count+=1
                    elif y==9:
                        if new_island_matrix[x+1][y]+ new_island_matrix[x-1][y]+new_island_matrix[x][y-1] == 1:
                            spike_count+=1
                    else:
                        if new_island_matrix[x+1][y]+ new_island_matrix[x-1][y]+new_island_matrix[x][y+1]+new_island_matrix[x][y-1] == 1:
                            spike_count+=1
    return spike_count                